$background = 040405
$onBackground = e3e2e4
$surface = 040405
$surfaceDim = 040405
$surfaceBright = 101010
$surfaceContainerLowest = 030304
$surfaceContainerLow = 070808
$surfaceContainer = 08090a
$surfaceContainerHigh = 0d0c0c
$surfaceContainerHighest = 0f0f0f
$onSurface = e3e2e4
$surfaceVariant = 131315
$onSurfaceVariant = c3c7ce
$outline = 8d9197
$outlineVariant = 43474d
$inverseSurface = e3e2e4
$inverseOnSurface = 2f3032
$shadow = 000000
$scrim = 000000
$surfaceTint = 1f2933
$primary = adc9e9
$primaryDim = c0ddfd
$onPrimary = 14324c
$primaryContainer = 84a0be
$onPrimaryContainer = 193750
$inversePrimary = 45617c
$primaryFixed = cee5ff
$primaryFixedDim = adc9e9
$onPrimaryFixed = 001d33
$onPrimaryFixedVariant = 2d4963
$secondary = bdc7d5
$secondaryDim = d9e3f2
$onSecondary = 27313c
$secondaryContainer = 404a55
$onSecondaryContainer = afb9c7
$secondaryFixed = d9e3f2
$secondaryFixedDim = bdc7d5
$onSecondaryFixed = 121c27
$onSecondaryFixedVariant = 3e4853
$tertiary = dfbbe2
$tertiaryDim = fdd6ff
$onTertiary = 412745
$tertiaryContainer = b492b7
$onTertiaryContainer = 452b4a
$tertiaryFixed = fdd6ff
$tertiaryFixedDim = dfbbe2
$onTertiaryFixed = 2a122f
$onTertiaryFixedVariant = 593d5d
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 5e7a96
$secondaryPaletteKeyColor = 6e7884
$tertiaryPaletteKeyColor = b492b7
$neutralPaletteKeyColor = 767779
$neutralVariantPaletteKeyColor = 73777d
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 5e7a96
$secondary_paletteKeyColor = 6e7884
$tertiary_paletteKeyColor = b492b7
$neutral_paletteKeyColor = 767779
$neutral_variant_paletteKeyColor = 73777d
$term0 = 080808
$term1 = 8383ff
$term2 = 44def5
$term3 = 75fcdd
$term4 = 83b0cf
$term5 = 8ea9ee
$term6 = 8cd3f3
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 89ecff
$term11 = c9fff3
$term12 = a9c5d6
$term13 = abbdf8
$term14 = a7e4ff
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = d0ddff
$mauve = 9bc2ff
$red = 97b2ff
$maroon = aebdf1
$peach = e0c2f9
$yellow = d0f9f4
$green = b6e7ff
$teal = bee5ff
$sky = b9e0ff
$sapphire = 92cdff
$blue = 86c1ff
$lavender = aacfff
$klink = 428cc9
$klinkSelection = 418cc9
$kvisited = 4580db
$kvisitedSelection = 4380da
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b6ed
$kpositiveSelection = 00b7eb
$text = e3e2e4
$subtext1 = c3c7ce
$subtext0 = 8d9197
$overlay2 = 1c1c1c
$overlay1 = 191919
$overlay0 = 161616
$surface2 = 121212
$surface1 = 0e0d0d
$surface0 = 060607
$base = 000001
$mantle = 000001
$crust = 000001
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
