[ColorEffects:Disabled]
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=62,99,131
BackgroundNormal=62,99,131
DecorationFocus=102,155,193
DecorationHover=109,166,206
ForegroundActive=143,184,213
ForegroundInactive=109,166,206
ForegroundLink=102,155,193
ForegroundNegative=192,28,40
ForegroundNeutral=230,97,0
ForegroundNormal=143,184,213
ForegroundPositive=38,162,105
ForegroundVisited=109,166,206

[Colors:Complementary]
BackgroundAlternate=49,54,59
BackgroundNormal=49,54,59
DecorationFocus=30,146,255
DecorationHover=61,174,230
ForegroundActive=143,184,213
ForegroundInactive=175,176,179
ForegroundLink=61,174,230
ForegroundNegative=231,76,60
ForegroundNeutral=253,188,75
ForegroundNormal=239,240,241
ForegroundPositive=46,204,113
ForegroundVisited=61,174,230

[Colors:Selection]
BackgroundAlternate=62,99,131
BackgroundNormal=76,123,157
DecorationFocus=102,155,193
DecorationHover=109,166,206
ForegroundActive=143,184,213
ForegroundInactive=109,166,206
ForegroundLink=143,184,213
ForegroundNegative=143,184,213
ForegroundNeutral=143,184,213
ForegroundNormal=143,184,213
ForegroundPositive=143,184,213
ForegroundVisited=143,184,213

[Colors:Tooltip]
BackgroundAlternate=30,51,71
BackgroundNormal=30,51,71
DecorationFocus=102,155,193
DecorationHover=109,166,206
ForegroundActive=143,184,213
ForegroundInactive=109,166,206
ForegroundLink=143,184,213
ForegroundNegative=143,184,213
ForegroundNeutral=143,184,213
ForegroundNormal=143,184,213
ForegroundPositive=143,184,213
ForegroundVisited=143,184,213

[Colors:View]
BackgroundAlternate=36,60,82
BackgroundNormal=25,43,54
DecorationFocus=102,155,193
DecorationHover=109,166,206
ForegroundActive=143,184,213
ForegroundInactive=109,166,206
ForegroundLink=102,155,193
ForegroundNegative=192,28,40
ForegroundNeutral=230,97,0
ForegroundNormal=143,184,213
ForegroundPositive=38,162,105
ForegroundVisited=109,166,206

[Colors:Window]
BackgroundAlternate=36,60,82
BackgroundNormal=25,43,58
DecorationFocus=102,155,193
DecorationHover=109,166,206
ForegroundActive=143,184,213
ForegroundInactive=109,166,206
ForegroundLink=102,155,193
ForegroundNegative=192,28,40
ForegroundNeutral=230,97,0
ForegroundNormal=143,184,213
ForegroundPositive=38,162,105
ForegroundVisited=109,166,206

[General]
ColorScheme=BreezeClassic
Name=KittyDark
shadeSortColumn=true
