background {
  monitor =
  path = /home/a7r/Pictures/Wallpapers/A7R-Wallpaper-1.png
  blur_passes = 3
}

input-field {
    monitor =
    size = 100, 30
    outline_thickness = 1
    dots_size = 0.37 
    dots_spacing = 0.15 
    fade_on_empty = false
    outer_color = rgba(134, 173, 201, 1)
    inner_color = rgba(0, 0, 0, 0.3)
    font_color = rgba(134, 173, 201, 1)
    halign = center
    valign = center
    position = 0, -37
}

label {
    monitor =
    text = $TIME12
    font_size = 70
    position = 0, 37
    halign = center
    valign = center
    color = rgba(134, 173, 201, 1)
}
