add_newline = true

format = """
╭─ $time $directory$git_branch$git_status$package $fill╮
╰─ $character"""

right_format = """❮ ─╯"""

[character]
success_symbol = "❯"
error_symbol = "❯"
vicmd_symbol = "❮"

[directory]
read_only = " "

[git_branch]
format = "on $symbol$branch "

[git_status]
format = "(\\[$all_status$ahead_behind\\] )"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[time]
disabled = false
time_format = "%I:%M %p" # 24-hour clock (HH:MM)
style = "dimmed white"
format = "$time "

[fill]
symbol = "─"
style = "plain"
