Net/ThemeName "KittyDark"
Net/IconThemeName "Cawnonical Mono-Glyph Icon Suite (KittyDark)"
Gtk/CursorThemeName "A7R-Cursor"
Net/EnableEventSounds 1
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
